package com.example.rigcointriva;
//CRY
public class gameQuestions {
    public String[] mode2Q = {"What are monoids?", "How hot is a 300-watt Halogen light bulb?",
            "What is the airspeed velocity of an unladen European swallow?", "What is the second last letter of the alphabet when going in reverse order"};

    public String[] mode2CA = {"A mathematical structure consisting of a set of elements", "970 degrees", "21.382 knots", "B"};

    public String[] mode2IA1 = {"A geometric circular face with no edges or vertices.", "960 degrees", "23 miles per hour", "C"};

    public String[] mode2IA2 = {"A group of animals that live and hunt together for survival.", "980 degrees F", "28,346.457 inches per minute", "D"};

    public String[] mode2IA3 = {"A weather phenomenon characterized by heavy rainfall and strong winds.", "990 degrees F", "12 meters per second", "A"};

    public String[] questions = {
            "What are monoids?",
            "How hot is a 300-watt Halogen light bulb?",
            "What is the airspeed velocity of an unladen European swallow?",
            "What is the second last letter of the alphabet when going in reverse order",
            "What is the average temperature of a 75W halogen light bulb?",
            "What is the average calorie count of a banana?",
            "Which of the following has Riggy not eaten for lunch at school before?",
            "How often does a blue whale's heart beat?",
            "What is it called when a solid turns directly to a gas?",
            "How many billion cups of tea per year does the UK drink anually?",
            "What is the capital of new york ",
            "What is Riggy's Discord username?",
            "Name the device that is used to dig holes:",
            "Why are prescription drug bottles orange?",
            "Which of the following films have won the academy award for best animated feature?",
            "If W was a word, how would you spell it in english?",
            "Who was Queen Elizabeth II",
            "What are the primary colors also used in human vision?",
            "What animal has the scientific name Acinonyx jubatus?",
            "In the TV series \"Breaking Bad\", The protagonist Walter White goes by what name?",
            "What is the name of the calendar we use today?",
            "What is the period of a sin(x) graph?",
            "Which of the following is NOT a category of the periodic table?",
            "Which is NOT a South American Country?",
            "Which of the following US states contains the Grand Canyon National Park",
            "what is the fastest land animal",
            "what is a monad",
            "What is Logan Pederson's password?",
            "Which of the following was NOT a tool used by pirates?",
            "What do you call the songs seafarers sang while sailing?",
            "Which of the following is NOT a real word according to the Oxford English Dictionary?",
            "Excluding Rotations and Reflections, how many different blocks are in Tetris? ",
            "What was the first fruit eaten on the moon?",
            "What is the current world record for number of hot dogs eaten in 10 minutes?",
            "How long is New Zealand’s Ninety Mile Beach?",
            "What does the word \"matrix \"mean in the Bible?",
            "What color is the ‘black box’ in an airplane?",
            "What causes a flamingo's pink colour?",
            "Through what part of the body do dogs sweat?",
            "What bird has the largest wingspan?",
            "How many other bones does a shark have excluding its teeth?",
            "On average, how long did it take to render one frame of Toy Story?",
            "In which year did the hit  game \"Minecraft\" start development?",
            "How long is one full Minecraft day in the real world?",
            "In terms of stats, which Pokémon is the most powerful?",
            "Which of the following is NOT a Pokémon?",
            "How many season of the Pokémon Animated Series are there?",
            "Namesake of BTN, who lives at [redacted]?",
            "How many Pokémon are there, according to the Pokémon.com website?",
            "What is the first Pokémon in the Pokédex?",
            "How many FIFA (soccer game series made by EA) games are there?",
            "What block does NOT reduce fall damage in Minecraft",
            "In terms of video games, what does DPS stand for?",
            "What Minecraft boss has more health?",
            "Which of the following is the alphabet correctly spelled backwards",
            "Who won the most recent Champions League?",
            "Who has won the most Ballon D'Ors (Best Player of the Year)?",
            "What is the name of Vancouver's soccer club?",
            "Which soccer league is known as the most competitive league?",
            "What is the capital of France? ",
            "Who invented the lightbulb? ",
            "What is the chemical symbol for gold on the periodic table?",
            "Who wrote the play \"Hamlet\"?",
            "Which of the following is NOT one of the Great Lakes?",
            "Who was the first U.S. president?",
            "What is the capital of Australia?",
            "What is the currency of Japan?",
            "Who composed the \"Moonlight Sonata\"?",
            "What is the tallest mountain in the solar system?",
            "Who wrote the book \"To Kill a Mockingbird\"? ",
            "What is the capital of China?",
            "Who was the first man to walk on the moon?",
            "What is the currency of Brazil?",
            "What is the national animal of Scotland?",
            "What is the capital of the moon?",
            "What is a gerund?",
            "What was the first fast food restaurant? ",
            "What is the national animal of the United States? ",
            "Which country has won the most World Cups?",
            "In which year was the first FIFA World Cup held?",
            "What is the world's largest country in terms of land area?",
            "Which country is home to the Great Barrier Reef?",
            "In which country is the Taj Mahal located?",
            "In which continent is the country of Madagascar located?",
            "Which country is home to the Serengeti National Park?",
            "In what year did the United States enter World War II?",
            "How many moons does Mars have?",
            "Who painted the Mona Lisa?",
            "In what year was the first iPhone released?",
            "How many legs do ants have?",
            "Who is the founder of luxury fashion brand Gucci? ",
            "What is the philosophical belief that life is meaningless and lacks purpose?",
            "Which of the following countries does NOT border Ukraine?",
            "What is George Orwell’s most sold novel?",
            "What does a flashing green light mean?",
            "How many UN recognized countries start with the letter ‘z’?",
            "How many water buckets do you need to make an infinite water source in the game Minecraft?",
            "Which of the following is NOT an Ancient Greek god?",
            "When a person is scared, their ears produce more of what?",
            "How many stomachs does a cow have?",
            "Which animal causes the most deaths each year?",
            "Which of the following characters has NOT been \"The Flash\"?",};

    public String[] correctAnswers = {"A mathematical structure consisting of a set of elements.",
            "970 degrees F",
            "21.382 knots",
            "B",
            "500 degrees Fahrenheit ",
            "89 calories",
            "Burrito",
            "8 - 10 times per minute ",
            "Sublimation",
            "36",
            "Albany ",
            "RigStar25",
            "Shovel",
            "To prevent UV light from degrading the contents",
            "Rango (2011)",
            "doubleyou",
            "The Queen of England",
            "Red, Blue, Green",
            "Cheetah",
            "Heisenberg ",
            "The Gregorian Calendar",
            "2pi",
            "Actinides",
            "Guatemala ",
            "Arizona",
            "Cheetah",
            "a software design pattern",
            "science12",
            "walking the plank",
            "Shanties ",
            "Phagocyst",
            "5",
            "Peach",
            "63",
            "55 miles",
            "Womb",
            "Orange",
            "Their diet",
            "Their paws",
            "Albatross",
            "0",
            "30 hours",
            "2009",
            "20 minutes",
            "Arceus",
            "Salamist",
            "25",
            "Nicholas",
            "905",
            "Bulbasaur",
            "28",
            "Wool Blocks",
            "Damage per second",
            "The warden",
            "ZYXWVUTSRQPONMLKJIHGFEDCBA",
            "Real Madrid CF",
            "Lionel Messi",
            "Vancouver Whitecaps FC",
            "England's Premier League",
            "Paris",
            "Thomas Edison",
            "Au",
            "William Shakespeare",
            "Lake Tahoe",
            "George Washington",
            "Canberra",
            "Yen ",
            "Ludwig van Beethoven",
            " Olympus Mons on Mars",
            "Harper Lee",
            "Beijing",
            "Neil Armstrong",
            "Brazilian Real",
            "Unicorn",
            "There is no capital of the moon",
            "a word with an \"ing\" ending in the subject of a sentence.",
            "White Castle",
            "Bald Eagle",
            "Brazil",
            "1930",
            "Russia",
            "Australia",
            "India",
            "Africa",
            "Tanzania",
            "1941",
            "2  ",
            "Leonardo da Vinci",
            "2007",
            "6",
            "Guccio Gucci",
            "Nihilism",
            "Lithuania",
            "1984",
            "Pedestrian activated light",
            "2",
            "1",
            "Janus",
            "Earwax",
            "4",
            "Mosquitos",
            "Alan Scott"};

    public String[] incorrectAnswer1 = {"A geometric circular face with no edges or vertices.",
            "960 degrees ",
            "23 miles per hour",
            "C",
            "270 degrees Celsius ",
            "90 calories",
            "Sandwich",
            "Once every ten seconds",
            "Evaporation",
            "1",
            "New York",
            "StupidIdiot",
            "Hammer",
            "To make them more accessible to colorblind people ",
            "Shrek 2 (2004)",
            "W",
            "Boris Johnson",
            "Red, Blue, Yellow",
            "Spider",
            "Captain Cook",
            "The Germanic Calendar",
            "pi",
            "Lanthanoids",
            "Guyana",
            "Colorado ",
            "Lion",
            "The name Manav, but misspelled.",
            "password",
            "Astrolabe",
            "Ballads",
            "Blench",
            "4",
            "Apple",
            "15",
            "90 miles",
            "Computer simulation someone is trapped in",
            "Black",
            "Naturally occures",
            "Their nose",
            "Condor",
            "184",
            "2 minutes",
            "2019",
            "15 minutes",
            "Mewtwo",
            "Probopass",
            "7",
            "logan pederson",
            "1005",
            "Pikachu",
            "22",
            "Haybales",
            "Dual power system",
            "The ender dragon",
            "ZYXVWUTSRQPONMLKJIHGFEDCBA",
            "Manchester City FC",
            "Cristiano Ronaldo",
            "Vancouver FC",
            "Spain's Laliga",
            "Rome",
            "Benjamin Franklin  ",
            "Ag",
            "Edgar Allan Poe",
            "Lake Huron",
            "John Adams",
            "Melbourne ",
            "Japanese Dollar",
            "Wolfgang Amadeus Mozart",
            "Mauna Kea on Earth",
            "J.D. Salinger",
            "Shanghai",
            "Buzz Lightyear",
            "Brazilian Dollar",
            "Dragon ",
            "Apollo",
            "A disease",
            "McDonald's",
            "Grizzly Bear",
            "England",
            "1950",
            "Canada",
            "Bahamas",
            "Indonesia",
            "South America",
            "Egypt",
            "1935 ",
            "4 ",
            "Michelangelo",
            "2011",
            "5",
            "Coco Chanel ",
            "Humanism",
            "Belarus",
            "To Kill A Mockingbird",
            "Light out of power, stop and proceed when safe",
            "0",
            "2",
            "Aristaeus",
            "Sweat",
            "5",
            "Sharks",
            "Wally West"};

    public String[] incorrectAnswer2 = {"A group of animals that live and hunt together for survival.",
            "980 degrees F",
            "28,346.457 inches per minute",
            "D",
            "528 Kelvin",
            "91 calories",
            "Pizza",
            "Once every fifteen seconds",
            "Deposition ",
            "2045680.2",
            "Buffalo",
            "RiggyIsAGamer",
            "Electric guitar",
            "So that mice mistake them for cheese",
            "The Croods (2013)",
            "VV",
            "Prince Phillip",
            "Magneta, Cyan, Yellow",
            "Hawk",
            "Gustavo Fring",
            "Greg's Calendar",
            "3pi/2",
            "Alkaline Earth Metals",
            "Uruguay",
            "Alaska",
            "Pineapple",
            "A type planet found 1.32 light years away",
            "loganspassword",
            "Lodestone",
            "Hymns ",
            "Caterwaul",
            "3",
            "Orange",
            "6",
            "73 miles",
            "Group of angels",
            "Pink",
            "Their climate",
            "Their tail",
            "Ostrich",
            "177",
            "8 minutes",
            "2008",
            "30 minutes",
            "Pikachu",
            "Comfey",
            "14",
            "nathan sedlack",
            "885",
            "Squirtle",
            "15",
            "Slime blocks",
            "Dynamic point selection",
            "They have the same health",
            "ZYXWVUTSRQPONMLKJllHGFEDCBA",
            "Liverpool FC",
            "Alphonso Davies",
            "Vancouver Athletic United",
            "USA and Canada's MLS",
            "Madrid",
            "Nikola Tesla",
            "Gd",
            "Charles Dickens",
            " Lake Michigan",
            "Thomas Jefferson",
            "Washington DC",
            "Euro",
            "Mariah Carey",
            "K2 on Earth",
            "Ernest Hemingway",
            "Tokyo",
            "Sputnick",
            "Peso",
            "Lion ",
            "Lunarville",
            "A cartoon character",
            "Burger King",
            "Alligator",
            "United States",
            "2023",
            "United States",
            "Philippines",
            "Pakistan",
            "Oceania",
            "Uganda",
            "1945 ",
            "0 ",
            "Vincent van Gogh",
            "1997",
            "4",
            "Ralph Lauren ",
            "Stoicism ",
            "Poland",
            "The Hunchback Of Notre Damn",
            "Lane closure ahead",
            "7",
            "3",
            "Nike",
            "Hypothalamus",
            "1",
            "Lions",
            "Jay Garrick"};

    public String[] incorrectAnswer3 = {"A weather phenomenon characterized by heavy rainfall and strong winds.",
            "990 degrees F",
            "12 meters per second",
            "A",
            "507.1% the average human body temperature in Fahrenheit",
            "85 calories",
            "Pasta",
            "10 - 12 times per minute",
            "Condensation ",
            "16",
            "Syracuse ",
            "RiggyPlays",
            "Diet Coke",
            "So they are perceived as dangerous and less people take medicine that is not prescribed to them",
            "Cars (2006)",
            "Dubbleew",
            "The Former CEO of Microsoft",
            "Red, Yellow, Green",
            "Lizard ",
            "Saul Goodman",
            "The Julius Calendar",
            "2",
            "Transition Metals",
            "Paraguay",
            "New York ",
            "Fork",
            "A type of math problem",
            "^is8(is,+-d'.Sd;>fs,yh?;aT6^gi*,'",
            "Spyglass",
            "Tunes",
            "Gubbins",
            "8",
            "Kiwi",
            "69",
            "67 miles",
            "A 4-dimensional object",
            "Blue",
            "Their age",
            "Their fur",
            "Penguin",
            "209",
            "7 hours",
            "2011",
            "1 hour",
            "Charizard",
            "Stunky",
            "12",
            "sina shams",
            "995",
            "Charmander",
            "12",
            "Beds",
            "Differential process system",
            "The wither",
            "ZYXWVUTSPQRONMLKJIHGFEDCBA",
            "FC Barcelona",
            "Adebayo Akinfenwa",
            "Forester United",
            "Italy's Serie A",
            "Berlin",
            "Isaac Newton ",
            "Go",
            "John Milton",
            "Lake Superior",
            "Donald Trump",
            "Sydney",
            "Pound",
            "Johann Sebastian Bach",
            "Mount Julupiatis on Jupiter",
            "Mark Twain",
            "Hong Kong",
            "Michael Scott",
            "Euro",
            "Hedgehog",
            "Moonbase Alpha D", "" +
            "A type of medicine notable for it's germ fighting abalities",
            "Wendy's",
            "Lion",
            "Argentina",
            "1879",
            "Brazil",
            "Trinidad and Tobago",
            "Iran",
            "Asia",
            "Ethiopia",
            "1947 ",
            "9",
            "Pablo Picasso",
            "2001",
            "8",
            "Giorgio Armani ",
            "Existentialism ",
            "Russia",
            "Heidi",
            "Construction ahead",
            "6",
            "4",
            "Priapus",
            "Melatonin",
            "2",
            "Cayotes",
            "Barry Allen"};
}
